### PR TITLE
Add VoxelClouds skybox

### PR DESCRIPTION
**Pull request by Treer**
Edit: Artistically the voxel clouds can probably be improved, but a new skybox will take some work. I'll leave this here and if I ever get around to improving it I'll update the PR.

Partly inspired by the [cubeworld clouds](https://i.redd.it/9h9vxmmb5fi51.png), which I've always wanted in MT - though this perlin-based implementation isn't nearly as cute, the idea is a skybox to reduce how jarring/apparent the render distance cut-off in Minetest screenshots usually is. It's using the MTG water texture though, so might not blend the ocean in so seamlessly with other games or texture packs.

[voxelclouds_thumb](https://cdn.pannellum.org/2.5/pannellum.htm#panorama=https://panoramas.minetest.land/voxelclouds.jpg&autoLoad=true)

Example with land:
[voxelclouds_example_thumb](https://cdn.pannellum.org/2.5/pannellum.htm#panorama=https://panoramas.minetest.land/voxelclouds_example.jpg&autoLoad=true)

This is how #70afd8 blends with the horizon:
voxelclouds_fog

The skybox jpgs are using arithmetic compression to knock their size down  (the skybox adds another 1.6 MB) - it seems to get big gains on those empty spaces and works on Minetest 5.3 so I'm assume the image library MT uses (or Irrlicht) supports arithmetic encoding, however browsers often don't support it, so these jpegs might not be viewable in github, 

(@sofar since github doesn't seem to tell me when there's a PR, and I doubt you'll ever check)

There's also an artistic option of removing the near clouds with gimp so only the far clouds are visible (with side-effect of improving compression), or removing the less-cloud-like shapes.

### CODE REVIEW

**Comment by SmallJoker** [comment]
Out of Firefox, the Ristretto image viewer and GIMP, only latter could open the newly added JPEG files.

> Error interpreting JPEG image file (Suspension not allowed here)

No idea what's going on there. Perhaps this compression format cannot be read by certain JPEG library versions?

**Comment by Treer** [comment]
> Perhaps this compression format cannot be read by certain JPEG library versions?

That's exactly what it will be. There's a lot of discussion on https://bugzilla.mozilla.org/show_bug.cgi?id=680385
(also https://bugs.chromium.org/p/chromium/issues/detail?id=669501#c7)

it gets the best compression, but the CPU cost is higher so encouraging its spread on the web has drawbacks, the principal developer of libjpeg-turbo also isn't very interested in it.

> I'm resolving this bug again for now. (Please don't read too much into "WONTFIX".) Before reopening, we'd need at least two browser vendors to commit to supporting arithmetic-coded JPEGs. Mozilla could be one of them, but we won't implement this without evidence that it's going to be interoperable in the future.

However, something about those skybox images meant arithmetic compression was getting more than its usual gains.

On a different topic, I think Minetest's perlin may be the wrong approach for these skybox clouds, and using worldedit to place handmade [cubeworld-style](https://user-images.githubusercontent.com/6390507/104083059-7c0d9d00-528f-11eb-9a8f-4e8cafe4c895.png) ones would be a better use of an extra skybox.

**Comment by sofar** [comment]
I like the idea. I would definitely be up for merging something like this, but I wonder if it's time to split out new sets of skyboxes into submods (that `depend` on `skybox` for the API and add new skybox definitions). I would also add a bunch of mood lighted versions (heavier clouds vs. almost clear, and modified light levels and fog colors) to make it a bit more complete (although if you're doing a submod, you could do whatever and just have one).

The jpeg compression ... that shouldn't be a hurdle for players, so I would stay away from not commonly supported encodings.

**Comment by Treer** [comment]
> I wonder if it's time to split out new sets of skyboxes into submods (that depend on skybox for the API and add new skybox definitions)

I think that's a good idea.

I don't want to give the impression I'll necessarily ever get around to making a cubeworld style skybox mod like I keep talking about, ~~but if you do decide to refactor skybox to allow extensions, can I request the api allows .png files as well as jpeg. (I've had need for that in the past)~~

Edit: whoops, I see it already provides `skybox.add()`. I do think support for .png has value, but since skybox doesn't need any alterations to enable submods, a new version just for .png support isn't worth your time.

> The jpeg compression ... that shouldn't be a hurdle for players, so I would stay away from not commonly supported encodings.

FWIW arithmetic compression isn't a hurdle for players - Minetest/Irrlicht handles it fine, the confusion arose from not being able to view the file in github with firefox

**Comment by sofar** [comment]
We would just need to pass an extra field with the extension to the add function. Not very complex and backwards compatible.

**Pull request closed without merging**
